version: 2

jobs:
  test-rails:
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - run: bundle --version
      - run: bundle install
      - run: bundle exec rails --version
      - run: bundle exec rake db:schema:load
      - run: bundle exec rails test

workflows:
  version: 2
  test:
    jobs:
      - test-rails
